name: Run test suite

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install pytest
      run: pip install pytest
      
    - name: Install pod
      run: python setup.py install

    - name: Run tests
      run: pytest
